### ISSUE TITLE
Image uploader

### ISSUE THREAD

**Issue by tarangdave** [FrugalInnovationHub/trace-client#4]
Design and implement an image uploader which uses either ask for capture or upload from the device. The selected image is converted to base64 and sent to the backend endpoint where the image information is stored in database.

Priority - High

**Comment by tarangdave** [comment]
https://www.npmjs.com/package/react-file-base64

Can use this component for converting uploaded image to base64

**Comment by niral2395** [comment]
https://stackoverflow.com/questions/52288332/how-to-send-a-jpg-image-to-the-server-with-react-camera  - this might help
